---
- name: build image and push to docker hub play
  hosts: ansible_host
  tasks:
  - name: remove image
    command: docker rmi presentnine/my-hello-world
    ignore_errors: true
  - name: build image
    command: docker build -t presentnine/my-hello-world ~/hello-world
#  - name: docker login
#    command: docker login -u <ID> -p <PW>
  - name: push image
    command: docker push presentnine/my-hello-world
